language: node_js
node_js:
  - node

script:
  - npm run test

  env:
    global:
      - secure: "GLxQjAPrEc/2k2UlxrX6ioONdsk8A/hTMCiya0E/TmpCd+f4k0tfprAoWO8qs7bKmwfu6WCCbbt0aONQvBjW6BkFYv8Fk3O0yipBwo7xC6k6iX2T/U/4repAH8ojanutG30UZFDF/e+tQoKBXMHdOw+BCLD9zXrTHaF0Jmj6+VI0GcuSDmRSrLvPRMTx36RCEqze+Z2I1aTATJ1OCImtcXl4WNOmv6vTXlu/NVX5FuDzpC8PfTxRpGC4TraAmw7E/LJQVEuZKXEth4t+i9XMYjFm/39YDqIQdANxtgM/P1PgSKHLcPMNHUqUOJ+gACpAPC+iVxEjAvD31vlzZ39+9uDPmaWin8Skhf6qEyXMs01aMTJc4zH6ucRUGuM2rawEDHy69XK3GtZpfFfTzLPESB0SPTbox6M6cSsGf2dTjZfA0nvYUt6EoQOJxGB0c4QOyDlpS2w+tTQo2H+z2WQEK1bzMmcyRwryU44AFevzGQnCr2E0AyUtFRV3OYoK6WXF6AKngurX2t6Pq8WP65UzcIGnG9ArjGgZlw1eYKKhok54HvXmtjcaLpzcKScj0SGrQyuUFa7ZVJSx46lM8NZDRdrG/BQeyZGLAkUpiHLx5b/Cc9G+XWknoN7x+buzP+vi5vzriPNR8NmWKt2EryNwbCO1bQZTY83UDuUfmkwexmQ="
      - CC_TEST_REPORTER_ID=673cdd5b696f4598097bf5f19d42b34818a2e52b62f6516b66773a36445041ef